### ISSUE TITLE
[QUESTION] clarify option "run two nodes"

### ISSUE THREAD

**Issue by subversivo58** [conradoqg/naivecoin#1]
In

     # Run two nodes
     $ node bin/naivecoin.js -p 3001 --name 1
     $ node bin/naivecoin.js -p 3002 --name 2 --peers http://localhost:3001

How to evict conflict case have two or more "equal names"?

I'm not sure about this but the "--peers" startup option would not make sense to fetch a listing on a referral server (loockup)? I say this to the basic example of BitCore that has a "hardcoded" listing and still uses a list of servers to do loockup for us. As an example of this I imagine a reference server responding with an ordered list of the nearest nodes (geographically).

I'm kind of lost about this, can you give me a light?

**Comment by conradoqg** [comment]
> How to evict conflict case have two or more "equal names"?

In this case, the name is used to log data and to create the folder that stores the blockchain and transactions.
If you run two nodes in the same directory, you need two different names, if you run in separated folders not. 
This exists to allow the node to be run from the same folder. Geth (node) from Ethereum uses an ID and you can set the data folder that stores the data.

> I'm not sure about this but the "--peers" startup option would not make sense to fetch a listing on a referral server (loockup)? I say this to the basic example of BitCore that has a "hardcoded" listing and still uses a list of servers to do loockup for us. As an example of this I imagine a reference server responding with an ordered list of the nearest nodes (geographically).

Yes, it makes sense to fetch a list from a hardcoded/lookup server/discovery service, I'm not sure how bitcoin/ethereum implements that. I'll check that. The only conceptual issue I can see is: what happens if the hardcoded/lookup server/discovery service is hacked? So probably you should connect to a trustworthy node at first and then expand from that.

The `--peers` serve to that purpose, you can set the initial node to connect with. After that, it broadcasts himself to that node and later it receives the list of all known nodes from every node that received your broadcast.

You could set more peers just by adding more `--peers` option.

**Comment by subversivo58** [comment]
I know it is not part of the question but I leave here the references (Bitcoin)

The user can also start their client by passing a list of IP's of nodes to which they should try to connect initially, but in this case you would have to know the IP of at least one node that already exists.
This is done through the `-addnode=<ip>` parameter. This parameter can be [found here](https://en.bitcoin.it/wiki/Running_Bitcoin#Command-line_arguments)

There is a list of domains maintained for the sole purpose of providing a list of IPs that are known to be running Bitcoin network nodes, and these domains are embedded in Bitcoin client code.
So just a DNS query on these domains to have a list of the initial nodes to connect to, and from them to go increasing the local base of known nodes.
You can see the [specific section of the code](https://github.com/bitcoin/bitcoin/blob/v0.14.2/src/chainparams.cpp#L123) where these domains are located, and the section [where the client makes the query](https://github.com/bitcoin/bitcoin/blob/v0.14.2/src/net.cpp#L1554)

There is also a list of IPs of the Bitcoin network nodes (hardcoded) in the code, which will be used if all other methods fail. This list can be seen in this [part of the code](https://github.com/bitcoin/bitcoin/blob/v0.14.2/src/chainparamsseeds.h#L10), and is used [here](https://github.com/bitcoin/bitcoin/blob/v0.14.2/src/net.cpp#L1705).

I do not know how Ethereum does it but I believe it follows the same logic
