### ISSUE TITLE
lowdb as a json replacement to existing file i/o

### ISSUE THREAD

**Issue by blinkcloud** [conradoqg/naivecoin#15]
Hi Conrad!

First, thank you for your contributions, we loved your example and think this covers a lot of the core concepts behind a cryptocurrency and is a great thing for the community.  I like the concept of storing a blockchain as a simple json structure and don't think it really needs to get more complicated than that, have you looked at lowdb at all? https://github.com/typicode/lowdb  We are considering it for a compact blockchain solution.

**Comment by conradoqg** [comment]
Hey

Thanks, man!

The very first implementation I used it, but after a while, I decided to use a simpler version where I could control the deserialization. Internally both works practically the same.

If you look [here](https://github.com/typicode/lowdb/blob/master/src/adapters/FileSync.js) it writes the whole file at once (like my solution). The ideal solution would be a real DBMS that writes the chunks instead of the whole file or is somewhat optimized to store/search tree-like data, like a graph database or something.

Best

**Comment by blinkcloud** [comment]
Thanks Conrad, 

We are playing around with mongoose + ES6 class support, you can essentially inject a class into a mongoose schema: http://mongoosejs.com/docs/advanced_schemas.html Going to do some more experimentation with it in the next few days and see if we can get it working nicely

**Comment by conradoqg** [comment]
Thanks! When it's done please consider pinging me so I can see what you did and how.
