### ISSUE TITLE
How to Premine?

### ISSUE THREAD

**Issue by CHOMNANP** [conradoqg/naivecoin#20]
Just curious how do we pre-mine?

I have create 1 wallet and 1 address from the wallet, but not sure how can I premine to that wallet.

**Comment by conradoqg** [comment]
Hey

Premine means that a certain address will start with a pre-defined amount of value. The current implementation doesn't support that and if you want to do this you should change the source and change the "genesis" block with output transactions pointing to that address. 

Best

**Comment by CHOMNANP** [comment]
Okay. I am kinda not understand that.
How about we send some coin from 1 wallet to another?
Any guideline we can initiate coin to a wallet.

Appreciate the effort on the project. This is really helping to understand this blockchain concept.

**Comment by conradoqg** [comment]
Haha, OK man, no problem.

If you want to mine some coin to an address and then send that coins to another address, look at the `Example (wallet, address, transaction, and mining)` in the README.md, there you can see how to create addresses, mine coin and do some transactions.

Best

**Comment by CHOMNANP** [comment]
Thank man.
Understood :)

**Comment by eaverdeja** [comment]
Hello conrado,

Im having a bit of trouble imagining the best way to implement the premining. One of the changes I would like to make is to stop empty blocks from being mined. Obviously to do that, the genesis transaction would need a valid output address so a certain node starts the network with premined coins, removing the need for empty block mining.

However, how does that play out when initializing several nodes? All the nodes wallets should be created before the blockchain initialization an arbritary node's wallet should be asked for its (first and only) public key, assigning the genesis output to that address?

**Comment by conradoqg** [comment]
Hi man!

> Im having a bit of trouble imagining the best way to implement the premining. One of the changes I would like to make is to stop empty blocks from being mined. Obviously to do that, the genesis transaction would need a valid output address so a certain node starts the network with premined coins, removing the need for empty block mining.

> However, how does that play out when initializing several nodes? All the nodes wallets should be created before the blockchain initialization an arbritary node's wallet should be asked for its (first and only) public key, assigning the genesis output to that address?

I think there are two good alternatives to do that:
- One is simply to set the genesis block with an output transaction to a known address (since the address is generated in a deterministic way, you can create a simple function to get an address from a password),  manually calculate the hash, sign the block and set it as the genesis block. Save that block as the genesis block of the network and distribute it. Meaning that every node in this network must have the same "genesis" block in its configuration.
- The alternative is to do that programatically at the start of the node (I think it's better). Meaning that the genesis block is created in the first execution and the caller must provide the address and signature. In theory the block hash will be equal since it's based on the same address and signature. Maybe we can even consider this the network ID (the resulting genesis block).

I would love to see this implemented in the v1.0.0 branch (or v1.1.0). I'm open to a well done PR about this.

Best
