### ISSUE TITLE
Open internet communication

### ISSUE THREAD

**Issue by milanobrtlik** [conradoqg/naivecoin#24]
Hello,

i understand that this implementation is not ready for production. Still, I wonder how nodes communicate with each other on an open Internet without knowing their IP addresses. You need DHT with network identification or something else?

**Comment by conradoqg** [comment]
You can read [here](http://chimera.labs.oreilly.com/books/1234000001802/ch06.html#_network_discovery) how Bitcoin does that. 

In summary, the Bitcoin node needs to know at least one other node or a DNS service, from there it gets more peers and connects to them.

Naivecoin does not have a DNS service for discovery since it's a simple implementation and if someone decides to put it into production, at the beginning, it will not need a DNS since the nodes does more or less the same function. 

Best

**Comment by milanobrtlik** [comment]
I agree that this question does not belong to the implementation of naivecoin. I'm just curious how nodes on the internet will know they belong to the same network. Maybe i should check P2P chat examples first.

**Comment by conradoqg** [comment]
They exchange a version ID in Bitcoin and an ID on Ethereum, that way they know if they belong to the same network.

**Comment by milanobrtlik** [comment]
I made a little research. Im totally confused with that P2P over nodejs, which is actually not P2P, because it needs some discovery method. Can you please make example for P2P networking?

**Comment by Jovonni** [comment]
Peer to peer as a concept isn't reliant on that implementation detail. Whether the P2P is hard coded, or discovery based, it’s still P2P.

Of course we can implement a BC network with hard coded P2P, but you get what I’m saying.

What are your thoughts on this Milan?

On Jan 25, 2018, at 11:42 AM, MilanObrtlik <notifications@github.com<mailto:notifications@github.com>> wrote:


I made a little research. Im totally confused with that P2P over nodejs, which is actually not P2P, because it needs some discovery method. Can you please make example for P2P networking?

**Comment by milanobrtlik** [comment]
I think that if there is a third party connecting the nodes together, the network can simply be turned off by turning off taht third party.

Is there a solution where nodes can connect themselves? Without help from outside?

**Comment by conradoqg** [comment]
Not sure. Maybe someone could give me ideas on how to do that and at the same time not increasing the coin complexity.
