### ISSUE TITLE
Vision for this project

### ISSUE THREAD

**Issue by Jovonni** [conradoqg/naivecoin#25]
What is your vision for this, read through everything, and I can see what you are doing. I am curious as to where you would like to take this -- I can help

**Comment by conradoqg** [comment]
Hey man

My main goal is to have something where a new corner can arrive and understand better how cryptocurrencies work (not conceptually, but programmatically) in a simplified way, this is a hard subject. This is why I try to keep it with less than 1500 lines.

If you read a book like [Mastering Bitcoin](http://chimera.labs.oreilly.com/books/1234000001802) you can get all information you need and in details, but it takes a long time to read and you can be overwhelmed with the amount of information.

Right now I'm trying to make sure that the Naivecoin works reliably without gaps, bugs or misconceptions (and meanwhile trying to be an expert in the matter). I try to simplify it where I can, for example, instead of Websockets it uses plain old REST API, instead of custom DB to store efficiently the blocks it uses a simple file storage. If someone shows me a bug or an undesirable behavior I try to improve/fix it.

One nice thing that people could help me with is the test coverage, right now I'm only testing the happy path, where everything works. It's a boring task, I tried to improve it a little bit this week.

Some people want to put it into production, but if one really wants to create a coin, it's better to fork Bitcoin/Litecoin/Ethereum itself. (Ethereum is the most feature-wide one and you can create exactly what you need using it, without forking and in a timely manner)

Next month I'm presenting this to some people (as an educational material) so this week I implemented a very simple UI to help me show visually the blockchain and make my "teaching" task easier.

My long goal (no date and no plan yet) is to fork the Naivecoin and create Naivecontract to mimic how Ethereum works. This could increase the project from 1500 to 2000-2500 lines because of the complexity. Basically, the idea is to implement scripting and data storage in the blockchain instead of a simple "amount" variable. I don't plan to put something like GAS (to cover the processing cost of the script) or deterministic script (to know the costs beforehand).

Best

**Comment by Jovonni** [comment]
Preaching to the Choir my friend!

I started off reading mastering bitcoin, and the bitcoin developer guide years ago. Since then I’ve tried every blockchain platform that exists basically. Forked bitcoin myself to run arbitrary functionality as practice over time, etc. I see and issue with all of them, and that’s the overhead that comes with them. None of them, can you just clone a repo, and hit go. Even with eth, the most widely used, there is SO much overhead, from the wallet, to the testnets, etc, so much, and their network gets congested so much. I’ve read all of their academic literature, including Gavin Woods “yellow paper”, and I loved the theoretically approach they were going for, but it has missed the mark in my opinion. I think there exists room for cleverly designed, lite approach to secure, reliable, and generalized blockchain implementation. I have already been writing a smart contract approach on top of multi chain, and bitcoin, for practice and I’d like to help take this to that stage. I was just going to clone the repo, and do it solo, but I think you are interested enough to collaborate from opposite ends of the world......

I really think we can do something good for the community here. And I understand trying to keep it light, but I don’t know wat light means now, I mean lighter than everything else lol. I’m refreshed to hear you have the same goal of implementing generalized contracts and a programming language on top. Seeing how ethereum did it from scratch and reading everything they ever wrote before people knew about them helped. I suggest read Gavin woods yellow paper, and vitaliks “pre history of ethereum”.. google then if unfamiliar. Lastly, I think GAS isn’t the only way to solve the halting problem in this case....

I always clone New blockchain implantation and try every platform, and my need for a simplified but reliably secure and generalized ecosystem exists with other people (that’s my assumption!)......Let’s do good for the world my friend... one stranger to another ✊🏽✊🏽


Sent from my iPhone

On Jan 23, 2018, at 10:15 AM, Conrado Quilles Gomes <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey man

My main goal is to have something where a new corner can arrive and understand better how cryptocurrencies work (not conceptually, but programmatically) in a simplified way, this is a hard subject. This is why I try to keep it with less than 1500 lines.

If you read a book like Mastering Bitcoin<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fchimera.labs.oreilly.com%2Fbooks%2F1234000001802&data=02%7C01%7Cjpharr2%40student.gsu.edu%7Cb2f33cafa2fb4320f5d008d562741b36%7C704d822c358a47849a1649e20b75f941%7C0%7C0%7C636523173167487044&sdata=s%2FBSsqtv0qz%2B9rDIX%2F%2FkpGQlLAxDGffoDvfoMR1xJuk%3D&reserved=0> you can get all information you need and in details, but it takes a long time to read and you can be overwhelmed with the amount of information.

Right now I'm trying to make sure that the Naivecoin works reliably without gaps, bugs or misconceptions (and meanwhile trying to be an expert in the matter). I try to simplify it where I can, for example, instead of Websockets it uses plain old REST API, instead of custom DB to store efficiently the blocks it uses a simple file storage. If someone shows me a bug or an undesirable behavior I try to improve/fix it.

One nice thing that people could help me with is the test coverage, right now I'm only testing the happy path, where everything works. It's a boring task, I tried to improve it a little bit this week.

Some people want to put it into production, but if one really wants to create a coin, it's better to fork Bitcoin/Litecoin/Ethereum itself. (Ethereum is the most feature-wide one and you can create exactly what you need using it, without forking and in a timely manner)

Next month I'm presenting this to some people (as an educational material) so this week I implemented a very simple UI to help me show visually the blockchain and make my "teaching" task easier.

My long goal (no date and no plan yet) is to fork the Naivecoin and create Naivecontract to mimic how Ethereum works. This could increase the project from 1500 to 2000-2500 lines because of the complexity. Basically, the idea is to implement scripting and data storage in the blockchain instead of a simple "amount" variable. I don't plan to put something like GAS (to cover the processing cost of the script) or deterministic script (to know the costs beforehand).

Best

**Comment by conradoqg** [comment]
Another thing that could be useful is to create a UI to use the API. So instead of someone calling all the APIs (or using swagger) it could use a UI separated by role, like Miner and Operator where the user can create the wallets, addresses, and transfer money. Nothing fancy just an easier way to deal with the coin.

Best

**Comment by Jovonni** [comment]
Duly noted! Let’s keep the communication open, send me your email if you don’t mind so we don’t have to keep talking over github publicly. Of if you want that’s fine too

Sent from my iPhone

On Jan 23, 2018, at 12:05 PM, Conrado Quilles Gomes <notifications@github.com<mailto:notifications@github.com>> wrote:


Another thing that could be useful is to create a UI to use the API. So instead of someone calling all the APIs (or using swagger) it could use a UI separated by role, like Miner and Operator where the user can create the wallets, addresses, and transfer money. Nothing fancy just an easier way to deal with the coin.

Best

**Comment by demenvil** [comment]
Exactly I'm developing a php SDK for creating a blockchain explorer and creating a wallet and sending / receiving coins.
I make available on github in not long time to finish.The exploitation of the sdk will be based on codeignitor 3

**Comment by Jovonni** [comment]
@demenvil is the php SDK for this project specifically, or general purpose? @conradoqg I shouldv'e just left my comments on here, but wanted to think strategically :) will leave them up though. 

**FYI**

Most (I believe all), of the Ethereum creators came together over the internet, when they caught wind of Vitaliks work. However, many of them were already working on their own stuff to do the same thing... just sayin'

@conradoqg just make sure your todos are up to date, and thats a good start for the ones interested.

**Comment by Jovonni** [comment]
Also, @conradoqg I'm glad you were thinking containerization early on. I jotted down some notes on orchestrating multiple containers of this to quickly spin up an actual network arbitrarily

**Comment by demenvil** [comment]
@Jovonni  yes for this project.
With the complete swagger recovery.

I also thought about a version with electron or equivalent to make a wallet

**Comment by Jovonni** [comment]
Sounds exciting!

Sent from my iPhone

On Jan 23, 2018, at 4:43 PM, Ghislain Ott <notifications@github.com<mailto:notifications@github.com>> wrote:


@Jovonni<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjovonni&data=02%7C01%7Cjpharr2%40student.gsu.edu%7C487efb128364443040de08d562aa59d2%7C704d822c358a47849a1649e20b75f941%7C0%7C0%7C636523406140978703&sdata=mRX0NIF6k8EfhIcjobtKyYdaIMCxWz%2FDi6YsV%2Fcie6Y%3D&reserved=0> yes for this project.
With the complete swagger recovery.

I also thought about a version with electron or equivalent to make a wallet

**Comment by conradoqg** [comment]
Nice! Let's keep in touch. You seem to know more about the subject than me.

I think to achieve your goal it's better to implement all the gaps
remaining (noted as // INFO in the source code) and change the way it
handles some parts (like moving it back to Websocket, and a better DB),
after that, review how bitcoin works and make sure that there are no
important problems with Naivecoin implementation (security related).

The only one problem I can see is the mining part. Doing that using
javascript it's a bad idea, or you change it to something else than
Proof-of-work, or implement the mining part in C++)

**Comment by conradoqg** [comment]
I'm gonna add to the README.MD the todos for this project as suggested by @Jovonni .

**Comment by conradoqg** [comment]
@Jovonni Let's keep talking publicly so more people can help if necessary. Thanks for your contact!

**Comment by jongear** [comment]
Arguably mining in javascript is not the worst idea. POW is relative to the
power of the network.  So if all nodes are running js miners, the hasrate
will be lower across the board so performance wise you should see no real
difference. The trick comes along if someone hooks in a homegrown c++
derived miner and inflates the mining hashrate beyond what the js powered
nodes can keep up with.   They won't have enough computation power to
overthrow the network but they will at least get bigger cuts of the mining
reward pie

-Jon

*Jon Gear*
p: 440.223.4186
e: askjon@jongear.io
b: JonGear.io <http://jongear.io/>

**Comment by Jovonni** [comment]
Proof of work is actually relative to computation power in general at its most fundamental form. The networking aspect comes into play when we are talking mining pools, and broadcasting “State” of the mining. However, POW is CPU bound, not network.

The trade offs from a design perspective will be mixing languages, and adding “complexity” simply from a homogenous standpoint. You’re points are correct though when we take into account groups mining together, and constantly telling eachother if a solution is found, and what segments of the solution space to ignore, etc.

Performance wise I’d like to experiment on the differences here. Anyone else interested?

**Comment by conradoqg** [comment]
I'm selecting features and adding milestones so people can follow the evolution of this cryptocoin

**Comment by eaverdeja** [comment]
Conrado, any updates on those milestones? I would love to join in on some organized effort :)

**Comment by Berkmann18** [comment]
Are there any plans in implementing a JS API that won't be using Swagger?
If yes, I'll be happy to help.

**Comment by conradoqg** [comment]
What do you mean by JS API? A CLI lib in JS?

**Comment by Berkmann18** [comment]
I meant having a JS version of it that wasn't relying on Swagger.

**Comment by crashbdx** [comment]
I think some people want us it in real world because in my case, as a front end javascript developper it just sound awesome to have a full javascript blockchain project that wouldnt require to learn a new language like Solidity etc. Is it what LISK do ? a full javascript blockchain project ? even though its more than that as its like a full ecosystem. If i can help in anyway on this project, testing for exemple, i would love to.

**Comment by eaverdeja** [comment]
Guys, I'm currently working on an GraphQL API for substituting the current API + docs. I'm also building a full frontend with React to consume the API. It will be possible to view the blockchain, create wallets, addresses and transactions and more. These are the first steps I planned out to make this project even more accessible.

Who's interested :) ?

**Comment by crashbdx** [comment]
Im very interested :)
