### ISSUE TITLE
What does it mean of "changeAddress" when "Create a new transaction"

### ISSUE THREAD

**Issue by votinhthuong** [conradoqg/naivecoin#36]
I see in your operator - Create a new transaction - that structure of this have a attribute named "changeAddress". I don't understand what it used for?

By the way, I also consider about the initial balance of every wallet at first time created. When you create a new wallet, it have nothing coin in it. And you say, if user want to have some coin, user must mining some blocks. But when in the blockchain, it only have one genesis block, so what thing I mine? Because when I try this situation, I still mined succesfull new block #1 without any transaction or pending block before in blockchain?

**Comment by conradoqg** [comment]
Change address is the address that should receive the "change" eg. you transfer 80 to someone using 100 from an unspent output transaction the "rest" or 20 will go to the change address.

If I'm not wrong, you can mine empty blocks (when there is no transaction pending), when you do that the miner will receive the reward for it. So you can do that to generate some coins before starting transactions.

**Comment by votinhthuong** [comment]
1. If I understand you right, so that "changeAddress" is the address of the miner who will mine successful for that transaction into block in blockchain, right?

2. Whether "mine empty blocks" does valid in blockchain? I considering with all real coin in the world that whether they allow miner to mine empty block for rewards?

**Comment by conradoqg** [comment]
> If I understand you right, so that "changeAddress" is the address of the miner who will mine successful for that transaction into block in blockchain, right?

No, the changeAddress existing only when creating a transaction (not mining it). The "Operator" creates a transaction and select an unspent transaction as the input of the transfer. In the end, a "change" will be left (if the total is less than the transfer amount). So the "Operator" transfer the rest to that change address.

> Whether "mine empty blocks" does valid in blockchain? I considering with all real coin in the world that whether they allow miner to mine empty block for rewards?

Mining empty blocks are not cool. That's why in the source-code I explicitly say that there's should be some kind of protection, like only allowing empty blocks if there aren't any available transactions. I'm open to suggestions (and PR's, hehe)
