### ISSUE TITLE
Syncing wallets between Nodes?

### ISSUE THREAD

**Issue by DimensionDevices** [conradoqg/naivecoin#41]
Is this possible? It seems that when I create a wallet on Node#1 it never reaches Node#2? The blocks sync fine, but the wallets do not - is this intended?

Cheers my dudes, you've done great work here btw :)

**Comment by conradoqg** [comment]
Thanks, man. 

The wallets shouldn't be synchronized because they are part of the "exchange"/"operator". Usually, you control your wallet in a local software (storing the private key in your PC) or using some service like coinbase.

If you sync wallets, every node (everyone) will know every private key created, it doesn't make sense.

Cheers

**Comment by DimensionDevices** [comment]
Ok groovy, that makes more sense now :) Thanks!

**Comment by DimensionDevices** [comment]
Sorry to reply after closure, would you know of an easy way to switch from Node based private keys to the local device?

**Comment by conradoqg** [comment]
You could change the naivecoin to store the private key in a file, instead of what it does now.

**Comment by DimensionDevices** [comment]
Yeah I gathered that much... Could you point me in the correct direction please?
You basically repeated what I asked.
