### ISSUE TITLE
Double spend

### ISSUE THREAD

**Issue by 0xs34n** [conradoqg/naivecoin#9]
If I create multiple transactions that are exactly the same without mining them, unspent transactions will be reused and lead to double spend

**Comment by conradoqg** [comment]
I'm gonna check that. This shouldn't be hard to fix.

Thanks!

**Comment by conradoqg** [comment]
Fixed in 57b011a60db84641377ef1174bf3861cb3a3f8b7

I still need to add two improvements. 

1. If the user tries to double spend, the miner will mine the block but the block will never be added to the blockchain thus locking the miner (it will try to mine the same block again).
2. When creating a transaction, it needs to check if that unspent output transaction doesn't already have a transaction using it (Not sure though).

What do you think?

**Comment by conradoqg** [comment]
Hey,

Now in d96154a8a85e2898358637190b89904649a5fd01, I added a feature to the miner to avoid invalid transactions, thus not locking it anymore.

Best
